# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"$\n\x14UpdatePrimaryRequest\x12\x0c\n\x04port\x18\x01 \x01(\t\"$\n\x15UpdatePrimaryResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32V\n\x06\x43lient\x12L\n\rUpdatePrimary\x12\x1c.client.UpdatePrimaryRequest\x1a\x1d.client.UpdatePrimaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEPRIMARYREQUEST']._serialized_start=24
  _globals['_UPDATEPRIMARYREQUEST']._serialized_end=60
  _globals['_UPDATEPRIMARYRESPONSE']._serialized_start=62
  _globals['_UPDATEPRIMARYRESPONSE']._serialized_end=98
  _globals['_CLIENT']._serialized_start=100
  _globals['_CLIENT']._serialized_end=186
# @@protoc_insertion_point(module_scope)
